import {
  Loader2,
  Chrome,
  Search,
  Target,
  TrendingUp,
  BarChart3,
  Users,
  Globe,
  Zap,
  Brain,
  FileText,
  Download,
  Settings,
  Plus,
  X,
  ChevronDown,
  ChevronRight,
  Filter,
  Calendar,
  Star,
  AlertCircle,
  CheckCircle,
  Clock,
  RefreshCw,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ExternalLink
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  google: Chrome,
  search: Search,
  target: Target,
  trending: TrendingUp,
  chart: BarChart3,
  users: Users,
  globe: Globe,
  zap: Zap,
  brain: Brain,
  fileText: FileText,
  download: Download,
  settings: Settings,
  plus: Plus,
  x: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  filter: Filter,
  calendar: Calendar,
  star: Star,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  clock: Clock,
  refresh: RefreshCw,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  externalLink: ExternalLink,
};